### ISSUE TITLE
Decode byte string Error

### ISSUE THREAD

**Issue by blluv** [Bindernews/thurgood#1]
An error occurs when attempting to decode a byte string.
ex)  "\x12\x34"
https://github.com/Bindernews/thurgood/blob/7ae39b48690e541e53da2dad9e6053d261f84f95/src/inner/deserialize.rs#L300

```
thread 'main' panicked at 'Parsing failed: Utf8(Utf8Error { valid_up_to: 1, error_len: Some(1) })', src\main.rs:9:37
```

```rust
fn main() {
    let f = File::open("Data/Scripts.rvdata").unwrap();
    let value_ruby = from_reader(f).expect("Parsing failed");
    let value_json = value_ruby.to_json().unwrap();
    println!("{}", serde_json::to_string_pretty(&value_json).unwrap());
}
```

```ruby
irb(main):005:0> Marshal.load(File.binread("Data/Scripts.rvdata"))
=>
[[31785027,
  "DEP \xE7\x84\xA1\xE5\x8A\xB9\xE5\x8C\x96"
...
```

**Comment by Bindernews** [comment]
Okay, what's the expected behavior? I feel like this should this be represented as an `RbRef::StrI`, but should raw byte strings *always* be converted to a `RbRef::StrI`, or do we test to see if it's UTF8 and then return an `RbRef::Str` else `RbRef::StrI`?

The other option is that raw strings are always `RbRef::StrI` and no encoding. This would be more consistent (so software expecting raw byte strings can always produce and consume `StrI`) but I feel it comes at a usability cost.

Can you tell me more about your use-case for the library and this issue in particular?
